-- Enriches the harbour directory from an official Estonian guest-harbour
-- registry export (veebikaart.ee) covering the whole coastline, not just
-- Tallinn bay. The source file had a partial encoding failure before it
-- reached this project: its header row and several categorical columns
-- (non-ASCII text, apparently Russian) were already replaced with literal
-- '?' bytes by an earlier export step -- unrecoverable, not a charset
-- guessing problem. What survived intact: harbour name, code, address,
-- GPS, phone, email, website, and an Estonian amenities list, which is
-- translated to English below. A handful of corrupted placeholder values
-- that leaked into website/email/phone/address ('not specified', garbled)
-- were cleaned to null rather than inserted as garbage text.

alter table harbour add column harbour_code varchar(10);
alter table harbour add column address text;
alter table harbour add column website varchar(255);
alter table harbour add column email varchar(255);
alter table harbour add column amenities text;
alter table harbour add column source_url text;

-- Real-world location correction: Kelnase is in Viimsi vald, not on
-- Prangli island as an earlier guess in this project assumed. Renaming
-- (not just fixing the address) because the old name is user-facing in
-- bot replies -- the substring "Kelnase" that /sail and /harbour match
-- on is preserved, so this doesn't break existing lookups.
update harbour set name = 'Kelnase (Viimsi)' where name = 'Kelnase (Prangli)';

-- 6 existing harbours enriched with authoritative contact
-- details and corrected coordinates from the registry export.
update harbour set lat = 59.5711333, lon = 24.7579667, harbour_code = 'EEAEN', address = 'Harju maakond, Tallinn, Kesklinna linnaosa, Tagamaa tee 1', website = 'tallinn.ee', email = 'tta@tallinnlv.ee', phone = '+372 6404618', amenities = null, source_url = 'https://veebikaart.ee/sadamad/aegna-sadam' where name = 'Aegna';
update harbour set lat = 59.4510472, lon = 24.6071306, harbour_code = 'EEKAK', address = 'Harju maakond, Tallinn, Haabersti linnaosa, Nooda tee 8', website = 'havenk.com', email = 'marina@havenk.com', phone = '+372 53700023', amenities = 'Shower, Electricity, Bike rental, Drinking water, Café/Restaurant, Fuel, Parking, Laundry, Bilge water reception, Waste disposal, Boat ramp, WC, Wi-Fi, Gantry crane 130t, CCTV', source_url = 'https://veebikaart.ee/sadamad/kakumae-sadam' where name = 'Kakumäe (Haven Kakumäe)';
update harbour set lat = 59.4663306, lon = 24.8301222, harbour_code = 'EEKJK', address = 'Harju maakond, Tallinn, Pirita linnaosa, Pirita tee 17', website = 'kjk.ee', email = 'sadam@kjk.ee', phone = '+372 530 10450', amenities = 'Vessel storage, Shower, Electricity, Drinking water, Café/Restaurant, Parking, Laundry, Minor repairs, Waste disposal, Boat ramp, WC, Wi-Fi', source_url = 'https://veebikaart.ee/sadamad/kalevi-jahtklubi-sadam' where name = 'Pirita (Kalevi Jahtklubi)';
update harbour set lat = 59.6371722, lon = 25.012, harbour_code = 'EEKLN', address = 'Harju maakond, Viimsi vald, Kelnase küla', website = 'viimsivald.ee', email = 'info@viimsivv.ee', phone = '+372 6028800', amenities = 'Electricity, Bike rental, Drinking water, Café/Restaurant, Fuel, Parking, Waste disposal, WC, Wi-Fi, Sewage pump-out', source_url = 'https://veebikaart.ee/sadamad/kelnase-sadam' where name = 'Kelnase (Viimsi)';
update harbour set lat = 59.4551667, lon = 24.737, harbour_code = 'EELEN', address = 'Harju maakond, Tallinn, Põhja-Tallinna linnaosa, Vesilennuki tn 6', website = 'jahisadam.eu', email = 'sadam@lennusadam.eu', phone = '+372 5022877', amenities = 'Vessel storage, Shower, Electricity, Wastewater reception, Boat rental, Drinking water, Café/Restaurant, Ship waste reception, Parking, Laundry, Waste disposal, Sauna, Boat ramp, Winter storage, WC, Wi-Fi, Playground, Boat cradle rental', source_url = 'https://veebikaart.ee/sadamad/lennusadam' where name = 'Lennusadam (Tallinn)';
update harbour set lat = 59.5562667, lon = 24.55415, harbour_code = 'EENAI', address = 'Harju maakond, Viimsi vald, Lõunaküla / Storbyn', website = 'saarteliinid.ee', email = 'info@saarteliinid.ee', phone = '+372 4530140', amenities = 'Shower, Bike rental, Café/Restaurant, Fuel, WC, Wi-Fi', source_url = 'https://veebikaart.ee/sadamad/naissaare-sadam' where name = 'Naissaare sadam';

-- 61 additional guest harbours from the national registry
-- (1 source row without usable GPS coordinates was skipped).
-- seaward_bearing_deg is left null (no reliable manual estimate for this
-- many coastlines) and depth_m is left null except where genuinely
-- recoverable from notes -- both already fall back gracefully in the app.
insert into harbour (name, lat, lon, harbour_code, address, website, email, phone, amenities, depth_m, source_url) values
  ('Alliklepa sadam', 59.2850806, 23.7936278, 'EEALI', 'Harju maakond, Lääne-Harju vald, Alliklepa küla, Päärbi', 'alliklepasadam.ee', 'info@alliklepasadam.ee', '+3725258735', 'Shower, Electricity, Drinking water, Parking, Laundry, Waste disposal, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/alliklepa-sadam'),
  ('Hara allveelaevade sadam', 59.5881417, 25.6126, 'EEHRS', 'Harju maakond, Kuusalu vald, Hara küla', 'harasadam.ee', 'sadam@harasadam.ee', '+37256900433', 'Shower, Electricity, Boat rental, Bike rental, Café/Restaurant, Fuel, Accommodation, Parking, Waste disposal, Sauna, Boat ramp, WC', null, 'https://veebikaart.ee/sadamad/hara-sadam-eehrs'),
  ('Kaberneeme sadam', 59.5200778, 25.2783972, 'EEKBN', 'Harju maakond, Jõelähtme vald, Kaberneeme küla, Kordoni tee 20', 'kaberneememarina.ee', 'info@kaberneememarina.ee', '+372 58 344 344', 'Shower, Electricity, Drinking water, Café/Restaurant, Fuel, Parking, Boat ramp, WC, Wi-Fi, Pressure washer access', 1.5, 'https://veebikaart.ee/sadamad/kaberneeme-sadam'),
  ('Koljunuki sadam', 59.5055556, 25.0899444, 'EEKLK', 'Harju maakond, Jõelähtme vald, Ülgase küla, Nuki tee 10', 'koljunuki.ee', 'sadam@koljunuki.ee', '+372 5235000', 'Electricity, Wastewater reception, Drinking water, Fuel, Parking, Bilge water reception, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/koljunuki-sadam'),
  ('Kurkse sadam', 59.2884833, 24.0222, 'EEKKE', 'Harju maakond, Lääne-Harju vald, Kurkse küla, Sadama', 'kurksesadam.ee', 'disanta66@gmail.com', '+372 5036425', 'Electricity, Boat rental, Bike rental, Drinking water, Parking, Waste disposal, Boat ramp, WC', null, 'https://veebikaart.ee/sadamad/kurkse-sadam'),
  ('Lohusalu sadam', 59.4028056, 24.2035833, 'EELSL', 'Harju maakond, Lääne-Harju vald, Lohusalu küla, Lohusalu tee 152', 'lohusalu.ee', 'lohusalu@lohusalu.ee', '+372 6771640', 'Shower, Electricity, Bike rental, Drinking water, Café/Restaurant, Fuel, Parking, Laundry, Waste disposal, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/lohusalu-sadam'),
  ('Miiduranna sadam', 59.4994, 24.8160778, 'EEMDR', 'Harju maakond, Viimsi vald, Miiduranna küla, Sadama', 'miidurannasadam.ee', 'kapten@miidurannasadam.ee', '+372 5247406', 'Electricity, Drinking water, Waste disposal', null, 'https://veebikaart.ee/sadamad/miiduranna-sadam'),
  ('Neeme sadam', 59.5314194, 25.1604611, 'EENME', 'Harju maakond, Jõelähtme vald, Neeme küla, Sadama tee 5', 'neememarina.ee', 'info@neememarina.ee', '+372 56 973 676', 'Shower, Electricity, Drinking water, Café/Restaurant, Fuel, Parking, Boat ramp, WC, Waste disposal', null, 'https://veebikaart.ee/sadamad/neeme-sadam'),
  ('Noblessneri sadam', 59.4545556, 24.7301111, 'EENOB', 'Harju maakond, Tallinn, Põhja-Tallinna linnaosa, Peetri tänav T5', 'noblessner.ee', 'port@noblessner.ee', '+372 5688 8825; +3726102105', 'Shower, Electricity, Drinking water, Laundry, WC', null, 'https://veebikaart.ee/sadamad/noblessneri-sadam'),
  ('Pirita sadam', 59.4688861, 24.8205889, 'EEPIR', 'Harju maakond, Tallinn, Pirita linnaosa, Purje tn 13', 'piritatop.ee', 'sadam@piritatop.ee', '+3726398800', 'Shower, Café/Restaurant, Fuel, Parking, Laundry, Waste disposal, Boat ramp, Wi-Fi', null, 'https://veebikaart.ee/sadamad/pirita-sadam'),
  ('Ristna sadam', 59.271, 23.7448333, 'EERST', 'Harju maakond, Lääne-Harju vald, Keibu küla, Tõnissoo', 'ristnasadam.ee', 'info@ristnasadam.ee', '+3725059038', 'Electricity, Drinking water, Waste disposal, Boat ramp', null, 'https://veebikaart.ee/sadamad/ristna-sadam'),
  ('Salmistu sadam', 59.4971083, 25.3674083, 'EESAM', 'Harju maakond, Kuusalu vald, Salmistu küla, Sadama tee 26', 'kuusalu.ee/salmistusadam', 'madis.praks@kuusalu.ee', '+372 5330 7301', 'Electricity, Wastewater reception, Drinking water, Bilge water reception, Boat ramp', null, 'https://veebikaart.ee/sadamad/salmistu-sadam'),
  ('Tilgu sadam', 59.4556833, 24.4875778, 'EETIL', 'Harju maakond, Harku vald, Meriküla', 'tmyc.ee', 'tilgusadam@mail.ee', '+372 5089340', 'Drinking water, Café/Restaurant, Parking, Boat ramp', null, 'https://veebikaart.ee/sadamad/tilgu-sadam'),
  ('Viinistu sadam', 59.6465611, 25.7548889, 'EEVIN', 'Harju maakond, Kuusalu vald, Viinistu küla, Ranna', 'viinistu.ee', 'sadam@viinistu.ee', '+37256229660', 'Shower, Hotel, Bike rental, Café/Restaurant, Accommodation, Boat ramp, Art museum', null, 'https://veebikaart.ee/sadamad/viinistu-sadam'),
  ('Eisma sadam', 59.5692972, 26.3042417, 'EEEIS', 'Lääne-Viru maakond, Haljala vald, Eisma küla', 'eismasadam.ee', 'info@eismasadam.ee', '+372 5131442', 'Shower, Electricity, Accessible toilet, Boat rental, Bike rental, Drinking water, Basketball court, Fuel, Accommodation, Laundry, Septic pump-out, Boat ramp, Tennis court, WC, Wi-Fi, Grill and picnic terrace, Fully equipped kitchen rental', null, 'https://veebikaart.ee/sadamad/eisma-sadam'),
  ('Käsmu majaka sadam', 59.6041167, 25.9237056, 'EEKSM', 'Lääne-Viru maakond, Haljala vald, Käsmu küla, Merekooli tn 5', 'käsmusadam.ee', 'sadam@kasmusadam.ee', '+37253302748', 'Bike rental, Café/Restaurant, Accommodation, Boat ramp', null, 'https://veebikaart.ee/sadamad/kasmu-majaka-sadam'),
  ('Narva kulgu sadam', 59.3443833, 28.1730806, 'EEKUG', 'Ida-Viru maakond, Narva linn, Kulgusadama tee 10', 'narvasadam.ee', 'info@narvasadam.ee', '+372 55699195', 'Parking, Boat ramp, WC', null, 'https://veebikaart.ee/sadamad/narva-kulgu-sadam'),
  ('Narva linnasadam', 59.3836417, 28.2060278, 'EEJOS', 'Ida-Viru maakond, Narva linn, Jõe tn 3', 'narvasadam.ee', 'info@narvasadam.ee', '+372 55699195; +372 58473132', 'Shower, Electricity, Hostel, Drinking water, Café/Restaurant, Accommodation, Parking, Laundry, Waste disposal, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/narva-linnasadam'),
  ('Purtse sadam', 59.4355583, 26.9929028, 'EEPUR', 'Ida-Viru maakond, Lüganuse vald, Purtse küla', null, null, null, null, null, 'https://veebikaart.ee/sadamad/purtse-sadam'),
  ('Toila sadam', 59.4266639, 27.5337083, 'EETOI', 'Ida-Viru maakond, Toila vald, Toila alevik, Sadama tee 2', 'idavirusadamad.ee/sadam/toila', 'sadam@toila.ee', '+372 56663590', 'Electricity, Drinking water, Café/Restaurant, Fuel, Parking, Laundry, Waste disposal, Pollutant reception, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/toila-sadam'),
  ('Vergi sadam', 59.5994861, 26.1012417, 'EEVER', 'Lääne-Viru maakond, Haljala vald, Vergi küla, Sadama tee 51', 'vergisadam.ee', 'lauri@vergisadam.ee', '+372 55567349', 'Electricity, Bike rental, Drinking water, Café/Restaurant, Parking, Waste disposal, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/vergi-sadam'),
  ('Võsu sadam', 59.586075, 25.9709194, 'EEVOS', 'Lääne-Viru maakond, Haljala vald, Võsu alevik, Piiri tn 6', 'vosusadam.ee', 'info@vosusadam.ee', '+372 5058145', 'Shower, Electricity, Drinking water, Café/Restaurant, Fuel, Parking, Laundry, Waste disposal, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/vosu-sadam'),
  ('Vasknarva uussadam', 59.0084889, 27.7362667, 'EEVUS', 'Ida-Viru maakond, Alutaguse vald, Vasknarva küla, Sõrenetsi tee 90', null, null, null, null, null, 'https://veebikaart.ee/sadamad/vasknarva-uussadam'),
  ('Dirhami sadam', 59.2113889, 23.5008472, 'EEDIR', 'Lääne maakond, Lääne-Nigula vald, Dirhami küla / Derhamn', 'dirhami.ee', 'info@dirhami.ee', '+372 4797221', 'Shower, Bike rental, Drinking water, Café/Restaurant, Fuel, Minor repairs, Waste disposal, Boat ramp, Phone, Wi-Fi', null, 'https://veebikaart.ee/sadamad/dirhami-sadam'),
  ('Hara sadam', 59.0897778, 23.5286528, 'EEHRA', 'Lääne maakond, Lääne-Nigula vald, Hara küla / Harga', 'laanenigula.ee', 'noarootsi@laanenigula.ee', '+372 472 4354', 'Parking, Boat ramp, Fire water intake point', null, 'https://veebikaart.ee/sadamad/hara-sadam'),
  ('Lääne sadam', 58.527275, 23.6766917, 'EELAN', 'Pärnu maakond, Lääneranna vald, Paatsalu küla, Reinu', 'rannamajad.ee', 'rein@paatsalu.ee', '+372 5028040', 'Electricity, Drinking water, Accommodation, Parking, Sauna', null, 'https://veebikaart.ee/sadamad/laane-sadam'),
  ('Paatsalu sadam', 58.5242, 23.6789694, 'EEPAA', 'Pärnu maakond, Lääneranna vald, Paatsalu küla, Polümeeri', 'paatsalu.ee', 'rein@paatsalu.ee', '+372 5028040', 'Shower, Electricity, Drinking water, Café/Restaurant, Accommodation, Parking, Laundry, Minor repairs, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/paatsalu-sadam'),
  ('Puise kalasadam', 58.7651361, 23.4545167, 'EEPIS', 'Lääne maakond, Haapsalu linn, Puise küla', null, 'taavi@parila-klaas.ee', '+372 513 6263', 'Electricity, Wastewater reception, Drinking water, Ship waste reception, Parking, Boat ramp', null, 'https://veebikaart.ee/sadamad/puise-kalasadam'),
  ('Suur-Holmi sadam', 58.9583472, 23.5270861, 'EESHL', 'Lääne maakond, Haapsalu linn, Westmeri tn 3', 'grandholmmarina.ee', 'aivar@ieg.ee', '+372 5652887', 'Vessel storage, Shower, Electricity, Bike rental, Drinking water, Café/Restaurant, Fuel, Sauna, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/suur-holmi-sadam'),
  ('Sviby sadam', 58.9700583, 23.3125306, 'EESVI', 'Lääne maakond, Vormsi vald, Sviby küla', 'saarteliinid.ee', 'info@saarteliinid.ee', '+372 4530140', 'Electricity, Waste disposal, Boat ramp, WC', null, 'https://veebikaart.ee/sadamad/sviby-sadam'),
  ('Westmeri sadam', 58.9604167, 23.5237222, 'EEWST', 'Lääne maakond, Haapsalu linn, Kaluri tn 32', 'morobell.ee', 'info@morobell.ee', '+372 5303 9129', 'Electricity, Wastewater reception, Drinking water, Ship waste reception, Waste disposal', null, 'https://veebikaart.ee/sadamad/westmeri-sadam'),
  ('Österby sadam', 58.97555, 23.5178639, 'EEOST', 'Lääne maakond, Lääne-Nigula vald, Österby küla', 'laanenigula.ee', 'noarootsi@laanenigula.ee', '+372 472 4350', 'Shower, Electricity, Drinking water, Café/Restaurant, Parking, Boat ramp', null, 'https://veebikaart.ee/sadamad/osterby-sadam'),
  ('Haldi sadam', 58.8066306, 22.4461222, 'EEHLD', 'Hiiu maakond, Hiiumaa vald, Haldi küla, Sadama', 'haldisadam.ee', 'info@haldisadam.ee', '+3725031734', 'Parking, Boat ramp', null, 'https://veebikaart.ee/sadamad/haldi-sadam'),
  ('Kalana sadam', 58.9209583, 22.0564778, 'EEKAL', 'Hiiu maakond, Hiiumaa vald, Kalana küla', null, 'jyri.tamm@jtholding.ee', '+3725211380', 'Café/Restaurant, Boat ramp', null, 'https://veebikaart.ee/sadamad/kalana-sadam'),
  ('Kärdla sadam', 59.0103333, 22.7543333, 'EEKDL', 'Hiiu maakond, Hiiumaa vald, Kärdla linn, Sadama tn 30', 'hiiumaasadamad.ee', 'sadamad@hiiumaa.ee', '+372 56662514', 'Vessel storage, Shower, Electricity, Wastewater reception, Maintenance services, Bike rental, Drinking water, Café/Restaurant, Fuel, Ship waste reception, Accommodation, RV parking, Parking, Laundry, Sauna, Boat ramp, Winter storage, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/kardla-sadam'),
  ('Kõrgessaare sadam', 58.993, 22.4643333, 'EEKRG', 'Hiiu maakond, Hiiumaa vald, Kõrgessaare alevik, Sadama tee 15', null, 'priit.post@esmarehitus.ee', '+372 5049165', 'Electricity, Parking, Boat ramp', null, 'https://veebikaart.ee/sadamad/korgessaare-sadam'),
  ('Orjaku sadam', 58.7885, 22.7708333, 'EEORJ', 'Hiiu maakond, Hiiumaa vald, Orjaku küla', 'sadamad.hiiumaa.ee', 'sadamad@hiiumaa.ee', '+372 53455059', 'Shower, Electricity, Bike rental, Drinking water, Café/Restaurant, Accommodation, Parking, Waste disposal, Sauna, Septic pump-out, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/orjaku-sadam'),
  ('Roograhu sadam', 58.9999444, 22.8200861, 'EERGR', 'Hiiu maakond, Hiiumaa vald, Hiiessaare küla, Roograhu', 'roograhu.ee', 'info@roograhu.ee', '+37253066615; +372 4636609', 'Shower, Electricity, Wastewater reception, Drinking water, Café/Restaurant, Ship waste reception, Accommodation, Laundry', null, 'https://veebikaart.ee/sadamad/roograhu-sadam'),
  ('Sõru sadam', 58.6906917, 22.5214556, 'EESRU', 'Hiiu maakond, Hiiumaa vald, Pärna küla, Liini', 'saarteliinid.ee', 'info@saarteliinid.ee', '+372 4530140', 'Electricity, Drinking water, Fuel, Minor repairs, Waste disposal, WC', null, 'https://veebikaart.ee/sadamad/soru-sadam'),
  ('Abruka sadam', 58.1626, 22.5276306, 'EEABR', 'Saare maakond, Saaremaa vald, Abruka küla, Sadama', 'saarteliinid.ee', 'info@saarteliinid.ee', '+372 4530140', 'Shower, Café/Restaurant, Laundry, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/abruka-sadam'),
  ('Atla sadam', 58.3018361, 21.8939, 'EEATL', 'Saare maakond, Saaremaa vald, Atla küla', 'atlasadam.eu', 'lymandasadamad@gmail.com', '+372 58 504 210', 'Electricity, Boat rental, Drinking water, Boat ramp, WC', null, 'https://veebikaart.ee/sadamad/atla-sadam'),
  ('Kungla sadam', 58.3627972, 22.9546722, 'EEKNG', 'Saare maakond, Saaremaa vald, Kungla küla', 'kunglasadam.ee', 'info@kunglasadam.ee', '+372 56472104', 'Electricity, Drinking water, Parking, Waste disposal, Boat ramp, WC', null, 'https://veebikaart.ee/sadamad/kungla-sadam'),
  ('Kuressaare sadam', 58.2440639, 22.4706028, 'EEKUR', 'Saare maakond, Saaremaa vald, Kuressaare linn, Tori tn 4', 'sadam.kuressaare.ee', 'sadam@kuressaare.ee', '+372 45 33 450', 'Vessel storage, Shower, Electricity, Bike rental, Drinking water, Café/Restaurant, Fuel, Laundry, Bilge water reception, Minor repairs, Sauna, Boat ramp, WC, Wi-Fi, Waste disposal', null, 'https://veebikaart.ee/sadamad/kuressaare-sadam'),
  ('Kõiguste sadam', 58.3696861, 22.971575, 'EEKGS', 'Saare maakond, Saaremaa vald, Kõiguste küla', 'koigustemarina.com', 'koigustemarina@gmail.com', '+3725580970', 'Car rental, Shower, Electricity, Boat rental, Bike rental, Drinking water, Café/Restaurant, Fuel, RV parking, Parking, Laundry, Waste disposal, Boat ramp, Camping, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/koiguste-sadam'),
  ('Lõmala sadam', 58.1730056, 22.1188306, 'EELMA', 'Saare maakond, Saaremaa vald, Lõmala küla', 'lomalasadam.ee', 'info@lomalasadam.ee', '+37256472104', 'Shower, Electricity, Wastewater reception, Bike rental, Drinking water, Ship waste reception, Parking, Laundry, Waste disposal, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/lomala-sadam'),
  ('Lõunaranna sadam', 58.5416667, 23.3166667, 'EELNR', 'Saare maakond, Muhu vald, Simiste küla', 'lounaranna.ee', 'olaf@lounaranna.ee', '+372 5036640', 'Car rental, Shower, Electricity, Boat rental, Bike rental, Drinking water, Café/Restaurant, Fuel, Accommodation, Laundry, Sauna, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/lounaranna-sadam'),
  ('Mõntu sadam', 57.9489306, 22.1271556, 'EEMNT', 'Saare maakond, Saaremaa vald, Mõntu küla, Mõntu kai', 'montusadam.ee', 'vrhl@hot.ee', '+372 4570570; +372 5145578', 'Electricity, Drinking water, Fuel', null, 'https://veebikaart.ee/sadamad/montu-sadam'),
  ('Orissaare sadam', 58.5623972, 23.0937028, 'EEORI', 'Saare maakond, Saaremaa vald, Orissaare alevik, Sadama tn 16', 'illiku.ee/sadam', 'sadamakapten@illiku.ee', '+372 56239358', 'Shower, Electricity, Boat rental, Bike rental, Drinking water, Café/Restaurant, Parking, Minor repairs, Waste disposal, Boat ramp, WC, Boat ramp (2)', null, 'https://veebikaart.ee/sadamad/orissaare-sadam'),
  ('Papissaare sadam', 58.3594889, 21.9852611, 'EEPAP', 'Saare maakond, Saaremaa vald, Rootsiküla', 'saarteliinid.ee', 'meelis.saarlaid@saarteliinid.ee', '(+372) 509 2932', 'Parking', null, 'https://veebikaart.ee/sadamad/papissaare-sadam'),
  ('Roomassaare sadam', 58.2174806, 22.5046167, 'EERMS', 'Saare maakond, Saaremaa vald, Kuressaare linn, Roomassaare tee 12', 'saarteliinid.ee', 'info@saarteliinid.ee', '+372 45 30140', 'Shower, Café/Restaurant, Fuel, Laundry, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/roomassaare-sadam'),
  ('Ruhnu/Ringsu sadam', 57.7799639, 23.2716444, 'EERNG', 'Saare maakond, Ruhnu vald, Ruhnu küla', 'saarteliinid.ee', 'info@saarteliinid.ee', '+372 4530140', 'Shower, Electricity, Bike rental, Café/Restaurant, Fuel, Laundry, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/ruhnu-sadam'),
  ('Soela sadam', 58.617275, 22.5932556, 'EESOE', 'Saare maakond, Saaremaa vald, Soela küla, Sadama', 'soelasadam.ee', 'info@soelasadam.ee', '+372 57 222 222', 'Electricity, Drinking water, Café/Restaurant, Fuel, Parking, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/soela-sadam'),
  ('Triigi sadam', 58.591925, 22.7195611, 'EETGI', 'Saare maakond, Saaremaa vald, Triigi küla, Saare', 'saarteliinid.ee', 'janis.osa@saarteliinid.ee', '+372 5302 6741', 'Shower, Electricity, Drinking water, WC', null, 'https://veebikaart.ee/sadamad/triigi-sadam'),
  ('Varese sadam', 58.5742889, 22.4000861, 'EEVRS', 'Saare maakond, Saaremaa vald, Pahapilli küla', 'varesesadam.ee', 'harry@windrose.ee', '+372 5066740', 'Electricity, Drinking water, Parking, Boat ramp, WC, Wi-Fi, Fishing gear storage shed', null, 'https://veebikaart.ee/sadamad/varese-sadam'),
  ('Vikati sadam', 58.3718287, 21.8620621, 'EEVIK', 'Saare maakond, Saaremaa vald, Vilsandi küla', 'saarteliinid.ee', 'meelis.saarlaid@saarteliinid.ee', '(+372) 509 2932', 'Parking', null, 'https://veebikaart.ee/sadamad/vikati-sadam'),
  ('Munalaiu sadam', 58.2292111, 24.1180028, 'EEMUN', 'Pärnu maakond, Pärnu linn, Lao küla', 'saarteliinid.ee', 'info@saarteliinid.ee', '+372 4530140', 'Shower, Parking, Laundry, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/munalaiu-sadam'),
  ('Pärnu Jahtklubi jahisadam', 58.38605, 24.4876611, 'EEPRV', 'Pärnu maakond, Pärnu linn, Lootsi tn 6/8', 'jahtklubi.ee', 'info@jahtklubi.ee', '+3724471750', 'Shower, Electricity, Bike rental, Drinking water, Café/Restaurant, Fuel, Parking, Laundry, Minor repairs, Boat ramp, WC, Wi-Fi, Fixed crane up to 10t', null, 'https://veebikaart.ee/sadamad/parnu-jahtklubi-jahisadam'),
  ('Suaru sadam', 58.1408278, 24.0174028, 'EESUA', 'Pärnu maakond, Kihnu vald, Lemsi küla', 'kihnu.kovtp.ee/sadam', 'sadam@kihnu.ee', '+372 55649365', 'Shower, Electricity, Drinking water, Fuel, Laundry, Boat ramp, WC', null, 'https://veebikaart.ee/sadamad/suaru-sadam'),
  ('Varbla sadam', 58.4318472, 23.6819, 'EEVPS', 'Pärnu maakond, Lääneranna vald, Rannaküla, Tamme 1', 'varblapuhkekyla.ee', 'varblapk@gmail.com', '+3725060892', 'Shower, Electricity, Boat rental, Bike rental, Drinking water, Café/Restaurant, Fuel, Parking, Laundry, Waste disposal, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/varbla-sadam'),
  ('Virtsu vanasadam', 58.5790111, 23.519325, 'EEVVS', 'Pärnu maakond, Lääneranna vald, Virtsu alevik, Tallinna mnt 31', null, 'mardo@kmet.ee', '+372 5030259', 'Parking', null, 'https://veebikaart.ee/sadamad/virtsu-vanasadam'),
  ('Värati sadam', 58.3092436, 23.9885186, 'EEVRI', 'Pärnu maakond, Pärnu linn, Värati küla', null, 'sufe@tostamaa.ee', '+372 5257934', 'Electricity, Café/Restaurant, Fuel, Parking, Waste disposal, Boat ramp, WC, Wi-Fi', null, 'https://veebikaart.ee/sadamad/varati-sadam');
